version: '3.8'
services:
  sqlServer:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@$$w0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
